---
root: true
extends: 
- airbnb
- plugin:flowtype/recommended
- plugin:react/recommended
- prettier
plugins:
- compat
- flowtype
- react
settings:
  import/parser: babel-eslint
  import/resolver:
    babel-module: {}
env:
  jest: true
  browser: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  arrow-body-style: 0 # allow braces with fat arrow functions
  brace-style: # no braces on same line
  - error
  - 1tbs
  - allowSingleLine: false
  class-methods-use-this: 1 # just warn if you don't use the this keyword in a class method
  compat/compat: 2 # eslint-plugin-compat
  flowtype/sort-keys: 2 # flowtype keys should be alphabetical
  func-names: 0 # ignore absent expression names
  import/no-extraneous-dependencies: 
  - error
  - packageDir: ./ # need to specify monorepo root
  import/prefer-default-export: 0 # this rule is getting in the way of consistency for some API libraries
  jsx-a11y/anchor-is-valid: 0 # ignore trying to force buttons instead of anchors
  jsx-a11y/click-events-have-key-events: 0 # too hard
  jsx-a11y/img-has-alt: 0 # eslint-plugin-jsx-a11y 5.0 seems to need this
  jsx-a11y/label-has-for: 0 # ignore when labels don't have `for` attribute
  jsx-a11y/no-static-element-interactions: 0 # allow onClick on <a> tags
  jsx-a11y/label-has-associated-control: 0
  lines-between-class-members: 0 # nah
  no-console: 0 # ignore if console statements are used (webpack strips them out of production js)
  no-empty:
  - 1
  -
    allowEmptyCatch: true
  no-multi-spaces: 1 # warn if multiple spaces are used
  no-param-reassign: 1 # only warn on param modification
  no-prototype-builtins: 0 # allow accessing hasOwnProperty on Object
  no-trailing-spaces: 0 # ignore trailing spaces
  no-underscore-dangle: 0 # allow giving objects keys that start with _
  object-shorthand: 1 # only warn if not using es6 object shorthand
  prefer-destructuring: 0 # nah
  react/default-props-match-prop-types: 0 # ensures that any defaultProp has a non-required PropType declaration
  react/destructuring-assignment: 0 # nah
  react/display-name: 0 # annoying
  react/forbid-prop-types: 1 # only warn for things like specifying objects as react proptypes
  react/jsx-filename-extension: 0
  react/jsx-no-bind: 1 # binding functions in render statements is bad for performance
  react/jsx-no-target-blank: 0 # this isn't as big of a security risk as eslint makes it seem
  react/jsx-one-expression-per-line: 0 # nah
  react/jsx-sort-props: # please alphabetize props in JSX and attributes in HTML
  - 1
  -
    ignoreCase: false
    reservedFirst: true
  react/jsx-wrap-multilines: 0 # nah
  react/no-access-state-in-setstate: 1
  react/no-did-mount-set-state: 0 # allow setState in componentDidMount()
  react/no-unknown-property: # taken care of by babel-react-plugin-html-attrs
  - 2
  - ignore:
    - class
    - for
  react/require-default-props: 0
  react/prefer-stateless-function: 1 # warn when component without lifecycle methods is not pure
  react/sort-comp: # order of component lifecycle methods doesn't matter
  - 1
  - order:
    - type-annotations
    - static-methods
    - lifecycle
    - everything-else
    - getters
    - render
  space-before-function-paren: 1 # warn when suboptimal spacing around function declarations
  vars-on-top: 0 # don't need to declare all variables at the top of a function
